// Generated by CoffeeScript 1.3.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['chaplin/mediator', 'chaplin/controllers/controller', 'chaplin/dispatcher'], function(mediator, Controller, Dispatcher) {
  'use strict';
  return describe('Dispatcher', function() {
    var TestController, dispatcher, freshParams, params, paramsId, route;
    dispatcher = params = null;
    paramsId = 0;
    route = {
      controller: 'test',
      action: 'show'
    };
    freshParams = function() {
      return params = {
        changeURL: false,
        id: paramsId++
      };
    };
    TestController = (function(_super) {

      __extends(TestController, _super);

      function TestController() {
        return TestController.__super__.constructor.apply(this, arguments);
      }

      TestController.prototype.historyURL = function(params) {
        return 'test/' + (params.id || '');
      };

      TestController.prototype.initialize = function(params, oldControllerName) {
        return TestController.__super__.initialize.apply(this, arguments);
      };

      TestController.prototype.show = function(params, oldControllerName) {};

      TestController.prototype.dispose = function(params, newControllerName) {
        return TestController.__super__.dispose.apply(this, arguments);
      };

      return TestController;

    })(Controller);
    define('controllers/test_controller', function(Controller) {
      return TestController;
    });
    beforeEach(function() {
      return freshParams();
    });
    it('should initialize', function() {
      return dispatcher = new Dispatcher();
    });
    it('should dispatch routes to controller actions', function() {
      var action, historyURL, initialize, proto;
      proto = TestController.prototype;
      historyURL = spyOn(proto, 'historyURL').andCallThrough();
      initialize = spyOn(proto, 'initialize').andCallThrough();
      action = spyOn(proto, 'show').andCallThrough();
      mediator.publish('matchRoute', route, params);
      expect(initialize).toHaveBeenCalledWith(params, null);
      expect(action).toHaveBeenCalledWith(params, null);
      return expect(historyURL).toHaveBeenCalledWith(params);
    });
    it('should start a controller anyway when forced', function() {
      var action, historyURL, initialize, proto;
      mediator.publish('matchRoute', route, params);
      proto = TestController.prototype;
      historyURL = spyOn(proto, 'historyURL').andCallThrough();
      initialize = spyOn(proto, 'initialize').andCallThrough();
      action = spyOn(proto, 'show').andCallThrough();
      params.forceStartup = true;
      mediator.publish('matchRoute', route, params);
      expect(initialize).toHaveBeenCalledWith(params, 'test');
      expect(initialize.callCount).toBe(1);
      expect(action).toHaveBeenCalledWith(params, 'test');
      expect(action.callCount).toBe(1);
      expect(historyURL).toHaveBeenCalledWith(params);
      return expect(historyURL.callCount).toBe(1);
    });
    it('should save the controller, action, params and url', function() {
      var d;
      mediator.publish('matchRoute', route, params);
      d = dispatcher;
      expect(d.previousControllerName).toBe('test');
      expect(d.currentControllerName).toBe('test');
      expect(d.currentController instanceof TestController).toBe(true);
      expect(d.currentAction).toBe('show');
      expect(d.currentParams).toBe(params);
      return expect(d.url).toBe("test/" + params.id);
    });
    it('should dispose inactive controllers and fire beforeControllerDispose events', function() {
      var beforeControllerDispose, dispose, passedController;
      dispose = spyOn(TestController.prototype, 'dispose').andCallThrough();
      beforeControllerDispose = jasmine.createSpy();
      mediator.subscribe('beforeControllerDispose', beforeControllerDispose);
      mediator.publish('matchRoute', route, params);
      expect(dispose).toHaveBeenCalledWith(params, 'test');
      passedController = beforeControllerDispose.mostRecentCall.args[0];
      expect(passedController instanceof TestController).toBe(true);
      expect(passedController.disposed).toBe(true);
      return mediator.unsubscribe('beforeControllerDispose', beforeControllerDispose);
    });
    it('should publish startupController events', function() {
      var passedEvent, startupController;
      startupController = jasmine.createSpy();
      mediator.subscribe('startupController', startupController);
      mediator.publish('matchRoute', route, params);
      passedEvent = startupController.mostRecentCall.args[0];
      expect(typeof passedEvent).toBe('object');
      expect(passedEvent.controller instanceof TestController).toBe(true);
      expect(passedEvent.controllerName).toBe('test');
      expect(passedEvent.params).toBe(params);
      expect(passedEvent.previousControllerName).toBe('test');
      return mediator.unsubscribe('startupController', startupController);
    });
    return it('should be disposable', function() {
      var initialize;
      expect(typeof dispatcher.dispose).toBe('function');
      dispatcher.dispose();
      initialize = spyOn(TestController.prototype, 'initialize');
      mediator.publish('matchRoute', route, params);
      expect(initialize).not.toHaveBeenCalled();
      expect(dispatcher.disposed).toBe(true);
      if (Object.isFrozen) {
        return expect(Object.isFrozen(dispatcher)).toBe(true);
      }
    });
  });
});
