// Generated by CoffeeScript 1.3.3

define(['chaplin/lib/support', 'chaplin/mediator', 'chaplin/models/model'], function(support, mediator, Model) {
  'use strict';
  return describe('mediator', function() {
    it('should be a simple object', function() {
      return expect(typeof mediator).toBe('object');
    });
    it('should have Pub/Sub methods', function() {
      expect(typeof mediator.subscribe).toBe('function');
      expect(typeof mediator.unsubscribe).toBe('function');
      return expect(typeof mediator.publish).toBe('function');
    });
    it('should have readonly Pub/Sub methods', function() {
      var methods;
      if (!(support.propertyDescriptors && Object.getOwnPropertyDescriptor)) {
        return;
      }
      methods = ['subscribe', 'unsubscribe', 'publish', 'on', 'off', 'trigger'];
      return _(methods).forEach(function(property) {
        var desc;
        desc = Object.getOwnPropertyDescriptor(mediator, property);
        expect(desc.enumerable).toBe(true);
        expect(desc.writable).toBe(false);
        return expect(desc.configurable).toBe(false);
      });
    });
    it('should publish messages to subscribers', function() {
      var eventName, payload, spy;
      spy = jasmine.createSpy();
      eventName = 'foo';
      payload = 'payload';
      mediator.subscribe(eventName, spy);
      mediator.publish(eventName, payload);
      expect(spy).toHaveBeenCalledWith(payload);
      return mediator.unsubscribe(eventName, spy);
    });
    return it('should allow to unsubscribe to events', function() {
      var eventName, payload, spy;
      spy = jasmine.createSpy();
      eventName = 'foo';
      payload = 'payload';
      mediator.subscribe(eventName, spy);
      mediator.unsubscribe(eventName, spy);
      mediator.publish(eventName, payload);
      return expect(spy).not.toHaveBeenCalledWith(payload);
    });
  });
});
