// Generated by CoffeeScript 1.4.0

define(['underscore', 'backbone', 'chaplin/lib/utils', 'chaplin/lib/event_broker'], function(_, Backbone, utils, EventBroker) {
  'use strict';

  var Dispatcher;
  return Dispatcher = (function() {

    Dispatcher.extend = Backbone.Model.extend;

    _(Dispatcher.prototype).extend(EventBroker);

    Dispatcher.prototype.previousControllerName = null;

    Dispatcher.prototype.currentControllerName = null;

    Dispatcher.prototype.currentController = null;

    Dispatcher.prototype.currentAction = null;

    Dispatcher.prototype.currentParams = null;

    Dispatcher.prototype.url = null;

    function Dispatcher() {
      this.initialize.apply(this, arguments);
    }

    Dispatcher.prototype.initialize = function(options) {
      if (options == null) {
        options = {};
      }
      this.settings = _(options).defaults({
        controllerPath: 'controllers/',
        controllerSuffix: '_controller'
      });
      this.subscribeEvent('matchRoute', this.matchRoute);
      return this.subscribeEvent('!startupController', this.startupController);
    };

    Dispatcher.prototype.matchRoute = function(route, params) {
      return this.startupController(route.controller, route.action, params);
    };

    Dispatcher.prototype.startupController = function(controllerName, action, params) {
      var handler, isSameController;
      if (action == null) {
        action = 'index';
      }
      if (params == null) {
        params = {};
      }
      if (params.changeURL !== false) {
        params.changeURL = true;
      }
      if (params.forceStartup !== true) {
        params.forceStartup = false;
      }
      isSameController = !params.forceStartup && this.currentControllerName === controllerName && this.currentAction === action && (!this.currentParams || _(params).isEqual(this.currentParams));
      if (isSameController) {
        return;
      }
      handler = _(this.controllerLoaded).bind(this, controllerName, action, params);
      return this.loadController(controllerName, handler);
    };

    Dispatcher.prototype.loadController = function(controllerName, handler) {
      var controllerFileName, path;
      controllerFileName = utils.underscorize(controllerName) + this.settings.controllerSuffix;
      path = this.settings.controllerPath + controllerFileName;
      if (typeof define !== "undefined" && define !== null ? define.amd : void 0) {
        return require([path], handler);
      } else {
        return handler(require(path));
      }
    };

    Dispatcher.prototype.controllerLoaded = function(controllerName, action, params, ControllerConstructor) {
      var controller, currentController, currentControllerName;
      currentControllerName = this.currentControllerName || null;
      currentController = this.currentController || null;
      if (currentController) {
        this.publishEvent('beforeControllerDispose', currentController);
        currentController.dispose(params, controllerName);
      }
      controller = new ControllerConstructor(params, currentControllerName);
      controller[action](params, currentControllerName);
      if (controller.redirected) {
        return;
      }
      this.previousControllerName = currentControllerName;
      this.currentControllerName = controllerName;
      this.currentController = controller;
      this.currentAction = action;
      this.currentParams = params;
      this.adjustURL(controller, params);
      return this.publishEvent('startupController', {
        previousControllerName: this.previousControllerName,
        controller: this.currentController,
        controllerName: this.currentControllerName,
        params: this.currentParams
      });
    };

    Dispatcher.prototype.adjustURL = function(controller, params) {
      var url;
      if (params.path || params.path === '') {
        url = params.path;
      } else if (typeof controller.historyURL === 'function') {
        url = controller.historyURL(params);
      } else if (typeof controller.historyURL === 'string') {
        url = controller.historyURL;
      } else {
        throw new Error('Dispatcher#adjustURL: controller for ' + ("" + this.currentControllerName + " does not provide a historyURL"));
      }
      if (params.changeURL) {
        this.publishEvent('!router:changeURL', url);
      }
      return this.url = url;
    };

    Dispatcher.prototype.disposed = false;

    Dispatcher.prototype.dispose = function() {
      if (this.disposed) {
        return;
      }
      this.unsubscribeAllEvents();
      this.disposed = true;
      return typeof Object.freeze === "function" ? Object.freeze(this) : void 0;
    };

    return Dispatcher;

  })();
});
