// Generated by CoffeeScript 1.4.0

define(['underscore', 'backbone', 'chaplin/lib/support', 'chaplin/lib/utils'], function(_, Backbone, support, utils) {
  'use strict';

  var mediator;
  mediator = {};
  mediator.subscribe = Backbone.Events.on;
  mediator.unsubscribe = Backbone.Events.off;
  mediator.publish = Backbone.Events.trigger;
  mediator.on = mediator.subscribe;
  mediator._callbacks = null;
  utils.readonly(mediator, 'subscribe', 'unsubscribe', 'publish', 'on');
  mediator.seal = function() {
    if (support.propertyDescriptors && Object.seal) {
      return Object.seal(mediator);
    }
  };
  utils.readonly(mediator, 'seal');
  return mediator;
});
