// Generated by CoffeeScript 1.3.1
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

define(['jquery', 'underscore', 'lib/utils', 'chaplin/views/view'], function($, _, utils, ChaplinView) {
  'use strict';

  var ChaplinCollectionView;
  return ChaplinCollectionView = (function(_super) {

    __extends(ChaplinCollectionView, _super);

    ChaplinCollectionView.name = 'ChaplinCollectionView';

    function ChaplinCollectionView() {
      this.renderAllItems = __bind(this.renderAllItems, this);

      this.showHideFallback = __bind(this.showHideFallback, this);

      this.itemsResetted = __bind(this.itemsResetted, this);

      this.itemRemoved = __bind(this.itemRemoved, this);

      this.itemAdded = __bind(this.itemAdded, this);
      return ChaplinCollectionView.__super__.constructor.apply(this, arguments);
    }

    ChaplinCollectionView.prototype.animationDuration = 500;

    ChaplinCollectionView.prototype.listSelector = null;

    ChaplinCollectionView.prototype.$list = null;

    ChaplinCollectionView.prototype.fallbackSelector = null;

    ChaplinCollectionView.prototype.$fallback = null;

    ChaplinCollectionView.prototype.loadingSelector = null;

    ChaplinCollectionView.prototype.$loading = null;

    ChaplinCollectionView.prototype.itemSelector = null;

    ChaplinCollectionView.prototype.filterer = null;

    ChaplinCollectionView.prototype.viewsByCid = null;

    ChaplinCollectionView.prototype.visibleItems = null;

    ChaplinCollectionView.prototype.getView = function(model) {
      throw new Error('CollectionView#getView must be overridden');
    };

    ChaplinCollectionView.prototype.getTemplateFunction = function() {};

    ChaplinCollectionView.prototype.initialize = function(options) {
      if (options == null) {
        options = {};
      }
      ChaplinCollectionView.__super__.initialize.apply(this, arguments);
      /*console.debug 'CollectionView#initialize', this, @collection, options
      */

      _(options).defaults({
        render: true,
        renderItems: true,
        filterer: null
      });
      this.viewsByCid = {};
      this.visibleItems = [];
      /*
            @bind 'visibilityChange', (visibleItems) ->
              console.debug 'visibilityChange', visibleItems.length
            @modelBind 'syncStateChange', (collection, syncState) ->
              console.debug 'syncStateChange', syncState
      */

      this.addCollectionListeners();
      if (options.filterer) {
        this.filter(options.filterer);
      }
      if (options.render) {
        this.render();
      }
      if (options.renderItems) {
        return this.renderAllItems();
      }
    };

    ChaplinCollectionView.prototype.addCollectionListeners = function() {
      this.modelBind('add', this.itemAdded);
      this.modelBind('remove', this.itemRemoved);
      return this.modelBind('reset', this.itemsResetted);
    };

    ChaplinCollectionView.prototype.itemAdded = function(item, collection, options) {
      if (options == null) {
        options = {};
      }
      return this.renderAndInsertItem(item, options.index);
    };

    ChaplinCollectionView.prototype.itemRemoved = function(item) {
      return this.removeViewForItem(item);
    };

    ChaplinCollectionView.prototype.itemsResetted = function() {
      return this.renderAllItems();
    };

    ChaplinCollectionView.prototype.render = function() {
      ChaplinCollectionView.__super__.render.apply(this, arguments);
      this.$list = this.listSelector ? this.$(this.listSelector) : this.$el;
      this.initFallback();
      return this.initLoadingIndicator();
    };

    ChaplinCollectionView.prototype.initFallback = function() {
      if (!this.fallbackSelector) {
        return;
      }
      this.$fallback = this.$(this.fallbackSelector);
      this.bind('visibilityChange', this.showHideFallback);
      return this.modelBind('syncStateChange', this.showHideFallback);
    };

    ChaplinCollectionView.prototype.showHideFallback = function() {
      var visible;
      visible = this.visibleItems.length === 0 && (typeof this.collection.isSynced === 'function' ? this.collection.isSynced() : true);
      return this.$fallback.css('display', visible ? 'block' : 'none');
    };

    ChaplinCollectionView.prototype.collectionIsSynced = function() {};

    ChaplinCollectionView.prototype.initLoadingIndicator = function() {
      if (!(this.loadingSelector && typeof this.collection.isSyncing === 'function')) {
        return;
      }
      this.$loading = this.$(this.loadingSelector);
      this.modelBind('syncStateChange', this.showHideLoadingIndicator);
      return this.showHideLoadingIndicator();
    };

    ChaplinCollectionView.prototype.showHideLoadingIndicator = function() {
      var visible;
      visible = this.collection.length === 0 && this.collection.isSyncing();
      return this.$loading.css('display', visible ? 'block' : 'none');
    };

    ChaplinCollectionView.prototype.filter = function(filterer) {
      var included, index, item, view, _i, _len, _ref;
      this.filterer = filterer;
      if (!_(this.viewsByCid).isEmpty()) {
        _ref = this.collection.models;
        for (index = _i = 0, _len = _ref.length; _i < _len; index = ++_i) {
          item = _ref[index];
          included = typeof filterer === 'function' ? filterer(item, index) : true;
          view = this.viewsByCid[item.cid];
          if (!view) {
            throw new Error('CollectionView#filter: ' + ("no view found for " + item.cid));
          }
          view.$el.stop(true, true).css('display', included ? '' : 'none');
          this.updateVisibleItems(item, included, false);
        }
      }
      return this.trigger('visibilityChange', this.visibleItems);
    };

    ChaplinCollectionView.prototype.renderAllItems = function() {
      var cid, index, item, items, remainingViewsByCid, view, _i, _j, _len, _len1, _ref;
      items = this.collection.models;
      this.visibleItems = [];
      remainingViewsByCid = {};
      for (_i = 0, _len = items.length; _i < _len; _i++) {
        item = items[_i];
        view = this.viewsByCid[item.cid];
        if (view) {
          remainingViewsByCid[item.cid] = view;
        }
      }
      _ref = this.viewsByCid;
      for (cid in _ref) {
        if (!__hasProp.call(_ref, cid)) continue;
        view = _ref[cid];
        if (!(cid in remainingViewsByCid)) {
          this.removeView(cid, view);
        }
      }
      for (index = _j = 0, _len1 = items.length; _j < _len1; index = ++_j) {
        item = items[index];
        view = this.viewsByCid[item.cid];
        if (view) {
          this.insertView(item, view, index, 0);
        } else {
          this.renderAndInsertItem(item, index);
        }
      }
      if (!items.length) {
        return this.trigger('visibilityChange', this.visibleItems);
      }
    };

    ChaplinCollectionView.prototype.renderAndInsertItem = function(item, index) {
      var view;
      view = this.renderItem(item);
      return this.insertView(item, view, index);
    };

    ChaplinCollectionView.prototype.renderItem = function(item) {
      var view;
      view = this.viewsByCid[item.cid];
      if (!view) {
        view = this.getView(item);
        this.viewsByCid[item.cid] = view;
      }
      view.render();
      return view;
    };

    ChaplinCollectionView.prototype.insertView = function(item, view, index, animationDuration) {
      var $list, $next, $previous, $viewEl, children, included, length, position, viewEl;
      if (index == null) {
        index = null;
      }
      if (animationDuration == null) {
        animationDuration = this.animationDuration;
      }
      position = typeof index === 'number' ? index : this.collection.indexOf(item);
      included = typeof this.filterer === 'function' ? this.filterer(item, position) : true;
      viewEl = view.el;
      $viewEl = view.$el;
      if (included) {
        if (animationDuration) {
          $viewEl.css('opacity', 0);
        }
      } else {
        $viewEl.css('display', 'none');
      }
      $list = this.$list;
      children = $list.children(this.itemSelector);
      length = children.length;
      if (length === 0 || position === length) {
        $list.append(viewEl);
      } else {
        if (position === 0) {
          $next = children.eq(position);
          $next.before(viewEl);
        } else {
          $previous = children.eq(position - 1);
          $previous.after(viewEl);
        }
      }
      view.trigger('addedToDOM');
      this.updateVisibleItems(item, included);
      if (animationDuration && included) {
        return $viewEl.animate({
          opacity: 1
        }, animationDuration);
      }
    };

    ChaplinCollectionView.prototype.removeViewForItem = function(item) {
      var view;
      this.updateVisibleItems(item, false);
      view = this.viewsByCid[item.cid];
      return this.removeView(item.cid, view);
    };

    ChaplinCollectionView.prototype.removeView = function(cid, view) {
      view.dispose();
      return delete this.viewsByCid[cid];
    };

    ChaplinCollectionView.prototype.updateVisibleItems = function(item, includedInFilter, triggerEvent) {
      var includedInVisibleItems, visibilityChanged, visibleItemsIndex;
      if (triggerEvent == null) {
        triggerEvent = true;
      }
      visibilityChanged = false;
      visibleItemsIndex = _(this.visibleItems).indexOf(item);
      includedInVisibleItems = visibleItemsIndex > -1;
      if (includedInFilter && !includedInVisibleItems) {
        this.visibleItems.push(item);
        visibilityChanged = true;
      } else if (!includedInFilter && includedInVisibleItems) {
        this.visibleItems.splice(visibleItemsIndex, 1);
        visibilityChanged = true;
      }
      if (visibilityChanged && triggerEvent) {
        this.trigger('visibilityChange', this.visibleItems);
      }
      return visibilityChanged;
    };

    ChaplinCollectionView.prototype.dispose = function() {
      /*console.debug 'CollectionView#dispose', this, 'disposed?', @disposed
      */

      var cid, prop, properties, view, _i, _len, _ref;
      if (this.disposed) {
        return;
      }
      this.collection.off(null, null, this);
      _ref = this.viewsByCid;
      for (cid in _ref) {
        if (!__hasProp.call(_ref, cid)) continue;
        view = _ref[cid];
        view.dispose();
      }
      properties = ['$list', '$fallback', '$loading', 'viewsByCid', 'visibleItems'];
      for (_i = 0, _len = properties.length; _i < _len; _i++) {
        prop = properties[_i];
        delete this[prop];
      }
      return ChaplinCollectionView.__super__.dispose.apply(this, arguments);
    };

    return ChaplinCollectionView;

  })(ChaplinView);
});
