// Generated by CoffeeScript 1.3.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

define(['chaplin/views/layout'], function(Layout) {
  'use strict';

  var ApplicationLayout;
  return ApplicationLayout = (function(_super) {

    __extends(ApplicationLayout, _super);

    ApplicationLayout.name = 'ApplicationLayout';

    function ApplicationLayout() {
      return ApplicationLayout.__super__.constructor.apply(this, arguments);
    }

    return ApplicationLayout;

  })(Layout);
});
