// Generated by CoffeeScript 1.3.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

define(['views/application_view', 'chaplin/views/collection_view'], function(ApplicationView, ChaplinCollectionView) {
  'use strict';

  var ApplicationCollectionView;
  return ApplicationCollectionView = (function(_super) {

    __extends(ApplicationCollectionView, _super);

    ApplicationCollectionView.name = 'ApplicationCollectionView';

    function ApplicationCollectionView() {
      return ApplicationCollectionView.__super__.constructor.apply(this, arguments);
    }

    ApplicationCollectionView.prototype.getTemplateFunction = ApplicationView.prototype.getTemplateFunction;

    return ApplicationCollectionView;

  })(ChaplinCollectionView);
});
