// Generated by CoffeeScript 1.4.0
var __hasProp = {}.hasOwnProperty;

define(['underscore', 'backbone', 'chaplin/lib/event_broker'], function(_, Backbone, EventBroker) {
  'use strict';

  var Controller;
  return Controller = (function() {

    Controller.extend = Backbone.Model.extend;

    _(Controller.prototype).extend(EventBroker);

    Controller.prototype.view = null;

    Controller.prototype.currentId = null;

    Controller.prototype.redirected = false;

    function Controller() {
      this.initialize.apply(this, arguments);
    }

    Controller.prototype.initialize = function() {};

    Controller.prototype.redirectTo = function(arg1, action, params) {
      this.redirected = true;
      if (arguments.length === 1) {
        return this.publishEvent('!router:route', arg1, function(routed) {
          if (!routed) {
            throw new Error('Controller#redirectTo: no route matched');
          }
        });
      } else {
        return this.publishEvent('!startupController', arg1, action, params);
      }
    };

    Controller.prototype.disposed = false;

    Controller.prototype.dispose = function() {
      var obj, prop, properties, _i, _len;
      if (this.disposed) {
        return;
      }
      for (prop in this) {
        if (!__hasProp.call(this, prop)) continue;
        obj = this[prop];
        if (obj && typeof obj.dispose === 'function') {
          obj.dispose();
          delete this[prop];
        }
      }
      this.unsubscribeAllEvents();
      properties = ['currentId', 'redirected'];
      for (_i = 0, _len = properties.length; _i < _len; _i++) {
        prop = properties[_i];
        delete this[prop];
      }
      this.disposed = true;
      return typeof Object.freeze === "function" ? Object.freeze(this) : void 0;
    };

    return Controller;

  })();
});
