// Generated by CoffeeScript 1.3.1

define(['underscore', 'lib/utils', 'chaplin/lib/support'], function(_, utils, chaplinSupport) {
  var support;
  support = utils.beget(chaplinSupport);
  return support;
});
