// Generated by CoffeeScript 1.3.1

define(['mediator', 'chaplin/dispatcher', 'chaplin/views/layout', 'chaplin/lib/router'], function(mediator, Dispatcher, Layout, Router) {
  'use strict';

  var Core;
  return Core = (function() {

    Core.name = 'Core';

    function Core() {}

    Core.prototype.title = '';

    Core.prototype.dispatcher = null;

    Core.prototype.layout = null;

    Core.prototype.router = null;

    Core.prototype.initialize = function() {
      /*console.debug 'Application#initialize'
      */
      return this.dispatcher = new Dispatcher();
    };

    Core.prototype.initRouter = function(routes, options) {
      this.router = new Router(options);
      if (typeof routes === "function") {
        routes(this.router.match);
      }
      return this.router.startHistory();
    };

    Core.prototype.disposed = false;

    Core.prototype.dispose = function() {
      /*console.debug 'Application#dispose'
      */

      var prop, properties, _i, _len;
      if (this.disposed) {
        return;
      }
      properties = ['dispatcher', 'layout', 'router'];
      for (_i = 0, _len = properties.length; _i < _len; _i++) {
        prop = properties[_i];
        this[prop].dispose();
        delete this[prop];
      }
      this.disposed = true;
      return typeof Object.freeze === "function" ? Object.freeze(this) : void 0;
    };

    return Core;

  })();
});
