define [
  'chaplin/application'
  'chaplin/mediator'
  'chaplin/dispatcher'
  'chaplin/controllers/controller'
  'chaplin/models/collection'
  'chaplin/models/model'
  'chaplin/views/layout'
  'chaplin/views/view'
  'chaplin/views/collection_view'
  'chaplin/lib/route'
  'chaplin/lib/router'
  'chaplin/lib/event_broker'
  'chaplin/lib/support'
  'chaplin/lib/sync_machine'
  'chaplin/lib/utils'
  'chaplin/composer'
], (Application, mediator, Dispatcher, Controller, Collection, Model, Layout, View, CollectionView, Route, Router, EventBroker, support, SyncMachine, utils, Composer) ->
  {
    Application,
    mediator,
    Dispatcher,
    Composer,
    Controller,
    Collection,
    Model,
    Layout,
    View,
    CollectionView,
    Route,
    Router,
    EventBroker,
    support,
    SyncMachine,
    utils
  }
