# Main entry point into Chaplin module.
# Load all components and expose them.
module.exports =
  Application:    require 'chaplin/application'
  Dispatcher:     require 'chaplin/dispatcher'
  Controller:     require 'chaplin/controllers/controller'
  Composer:       require 'chaplin/composer'
  Composition:    require 'chaplin/lib/composition'
  Collection:     require 'chaplin/models/collection'
  Model:          require 'chaplin/models/model'
  Layout:         require 'chaplin/views/layout'
  View:           require 'chaplin/views/view'
  CollectionView: require 'chaplin/views/collection_view'
  Route:          require 'chaplin/lib/route'
  Router:         require 'chaplin/lib/router'
  EventBroker:    require 'chaplin/lib/event_broker'
  helpers:        require 'chaplin/lib/helpers'
  mediator:       require 'chaplin/mediator'
  support:        require 'chaplin/lib/support'
  utils:          require 'chaplin/lib/utils'
