// Generated by CoffeeScript 1.3.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

define(['chaplin/controllers/controller'], function(ChaplinController) {
  'use strict';

  var ApplicationController;
  return ApplicationController = (function(_super) {

    __extends(ApplicationController, _super);

    ApplicationController.name = 'ApplicationController';

    function ApplicationController() {
      return ApplicationController.__super__.constructor.apply(this, arguments);
    }

    ApplicationController.prototype.title = 'Default title';

    return ApplicationController;

  })(ChaplinController);
});
